// examples/angular/minimal-example/src/app/app.component.ts
import { Component, OnInit } from "@angular/core";
import KRGlue from "@lyracom/embedded-form-glue";
import axios from 'axios'

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent implements OnInit {
  title = "minimal-example";
  message = null;

  ngOnInit() {
    const endpoint = "CHANGE_ME: JAVASCRIPT ENDPOINT";
    const publicKey = "CHANGE_ME: YOUR PUBLIC KEY";
    let formToken = "DEMO-TOKEN-TO-BE-REPLACED";

    axios
      .post('http://localhost:3000/createPayment', {
        paymentConf: { amount: 10000, currency: 'USD' }
      })
      .then(resp => {
        formToken = resp.data
        return KRGlue.loadLibrary(endpoint, publicKey) /* Load the remote library */
      })
      .then(({ KR }) =>
        KR.setFormConfig({
          /* set the minimal configuration */
          formToken: formToken,
          "kr-language": "en-US" /* to update initialization parameter */
        })
      )
      .then(({ KR }) =>
        KR.onSubmit(paymentData => {
          axios
            .post('http://localhost:3000/validatePayment', paymentData)
            .then(response => {
              if (response.status === 200)
                this.message = 'Payment successful!'
            })
          return false // Return false to prevent the redirection
        })
        )
      .then(({ KR }) =>
        KR.addForm("#myPaymentForm")
      ) /* add a payment form  to myPaymentForm div*/
      .then(({ KR, result }) =>
        KR.showForm(result.formId)
      ) /* show the payment form */
      .catch(
        error => (this.message = error + " (see console for more details)")
      );
  }
}

<div class="form">
  <h1>{{ title }}</h1>
  <div class="container">
    <div id="myPaymentForm"></div>
    <div>{{ message }}</div>
  </div>
</div>

// examples/react/minimal-example/src/App.js
import React, { Component } from 'react'
import KRGlue from '@lyracom/embedded-form-glue'
import axios from 'axios'
import './App.css'

class App extends Component {
  state = { message: null }

  render() {
    return (
      <div className="form">
        <h1>Payment form</h1>
        <div className="container">
          <div id="myPaymentForm"></div>
          <div>{this.state.message}</div>
        </div>
      </div>
    )
  }

  componentDidMount() {
    const endpoint = 'CHANGE_ME: JAVASCRIPT ENDPOINT'
    const publicKey = 'CHANGE_ME: YOUR PUBLIC KEY'
    let formToken = 'DEMO-TOKEN-TO-BE-REPLACED'

    // Generate the form token
    axios
      .post('http://localhost:3000/createPayment', {
        paymentConf: { amount: 10000, currency: 'USD' }
      })
      .then(resp => {
        formToken = resp.data
        return KRGlue.loadLibrary(
          endpoint,
          publicKey
        ) /* Load the remote library */
      })
      .then(({ KR }) =>
        KR.setFormConfig({
          /* set the minimal configuration */
          formToken: formToken,
          'kr-language': 'en-US' /* to update initialization parameter */
        })
      )
      .then(({ KR }) =>
        KR.onSubmit(paymentData => {
          axios
            .post('http://localhost:3000/validatePayment', paymentData)
            .then(response => {
              if (response.status === 200)
                this.setState({ message: 'Payment successful!' })
            })
          return false // Return false to prevent the redirection
        })
      ) // Custom payment callback
      .then(({ KR }) =>
        KR.addForm('#myPaymentForm')
      ) /* add a payment form  to myPaymentForm div*/
      .then(({ KR, result }) =>
        KR.showForm(result.formId)
      ) /* show the payment form */
      .catch(error =>
        this.setState({
          message: error + ' (see console for more details)'
        })
      )
  }
}

export default App
