// frameworks/angular/integration/src/app/app.component.ts
declare var window:any;
declare var JSON:any;

import { Component, AfterViewChecked, ChangeDetectorRef } from '@angular/core';
import KRGlue from "@lyracom/embedded-form-glue";
import _ from "underscore";

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})

export class AppComponent implements AfterViewChecked {
    called:boolean = false;
    response:any = null;

    constructor(private ref: ChangeDetectorRef) {}

    ngAfterViewChecked() {
        if (!this.called) {
            this.called = true;
            this.createKrypton();
        }
    }

    createKrypton() {
        const self:any = this;
        const ref:ChangeDetectorRef = this.ref;
        const getQuery:any = function() {
            let queryString:any = window.location.href.split("?")[1];
            let query:any = {};

            let segments:any = queryString.split("&");
            _.each(segments, segment => {
                let splittedSegment = segment.split("=");
                query[splittedSegment[0]] = splittedSegment[1];
            });
            return query;
        };

        let query:any = getQuery();
        let formToken:string = query.formToken;
        let endpoint:string = query.endpoint;
        let publicKey:string = query.publicKey;

        KRGlue.loadLibrary('http://krypton.local', publicKey)
            .then(KR => KR.setFormConfig({
                formToken,
            }))
            .then(KR => {
                KR.onSubmit((response:any) => {
                    self.response = JSON.stringify(response);
                    ref.detectChanges();
                });
                return KR.addForm('#myPaymentForm');
            })
            .then(KR => {
                KR.showForm(KR.result.formId);
            }).catch(err => {
                console.log(err);
            });
    }
}

<div style="text-align:center">
    <h1>
        Payment form
    </h1>
    <div id="myPaymentForm"></div>
    <pre *ngIf="response">{{response}}</pre>
</div>

// frameworks/react/integration/src/App.js
import React, { Component } from 'react';
import KRGlue from "@lyracom/embedded-form-glue";
import _ from "underscore";
import './App.css';

const getQuery = function() {
    let queryString = window.location.href.split("?")[1];
    let query = {};

    let segments = queryString.split("&");
    _.each(segments, segment => {
        let splittedSegment = segment.split("=");
        query[splittedSegment[0]] = splittedSegment[1];
    });


    return query;
};

let query = getQuery();
let formToken = query.formToken;
let endpoint = query.endpoint;
let publicKey = query.publicKey;
let pre;

class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            response: null,
        };
    }
  render() {
    return (
      <div className="App">
        <header className="App-header">
            <h1>Payment form</h1>
        </header>
        <div id="myPaymentForm"></div>
        <pre>{this.state.response}</pre>
      </div>
    );
  }
    componentDidMount() {
        const _this = this;
      KRGlue.loadLibrary(endpoint, publicKey).then(KR => {
          return KR.setFormConfig({
              formToken,
          });
      }).then(KR => {
          KR.onSubmit(response => {
              _this.setState({
                  response: JSON.stringify(response),
              });
          });
          return KR.addForm("myPaymentForm");
      }).then(KR => {
          return KR.showForm(KR.result.formId);
      }).catch(err => {
          console.log({err});
      });
    }
}

export default App;
